import 'package:flutter/foundation.dart';

/// Current language used throughout CropNexa.
final ValueNotifier<String> appCurrentLanguage =
    ValueNotifier<String>('English');

class AppLocalization {
  static const Map<String, Map<String, String>> translations = {
    // ============================================================
    // ENGLISH
    // ============================================================
    'English': {
      'home': 'Home',
      'my_farm': 'My Farm',
      'notifications': 'Notifications',
      'settings': 'Settings',
      'profile': 'Profile',
      'ai_assistant': 'AI Assistant',
      'crop_doctor': 'Crop Doctor',
      'dashboard': 'Dashboard',
      'market_prices': 'Market Prices',
      'price_forecast': 'Price Forecast',
      'farm_planner': 'Farm Planner',
      'expenses': 'Expenses',
      'crop_timeline': 'Crop Timeline',
      'ai_farm_intelligence': 'AI Farm Intelligence',

      'welcome': 'Welcome',
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'protect_crop': 'Protect your crop. Grow smarter.',
      'smart_farming': 'Smart Farming Intelligence',

      'continue': 'Continue',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'search': 'Search',
      'add': 'Add',
      'close': 'Close',
      'back': 'Back',
      'next': 'Next',
      'done': 'Done',

      'language': 'Language',
      'choose_language': 'Choose Your Language',
      'select_language': 'Select Language',

      'location': 'Location',
      'farm': 'Farm',
      'crop': 'Crop',
      'weather': 'Weather',
      'market': 'Market',
      'profile_title': 'Your Profile',
      'account': 'Account',
      'privacy': 'Privacy',
      'security': 'Security',
      'logout': 'Logout',

      'login': 'Login',
      'register': 'Create Account',
      'forgot_password': 'Forgot Password',
      'email': 'Email',
      'phone': 'Phone',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'full_name': 'Full Name',

      // Home page
      'current_location': 'Current Location',
      'your_farm': 'Your Farm',
      'your_crops': 'Your Crops',
      'farm_health': 'Farm Health',
      'healthy': 'Healthy',
      'attention_needed': 'Attention Needed',
      'weather_alert': 'Weather Alert',
      'farm_alert': 'Farm Alert',
      'no_alerts': 'No alerts right now',
      'temperature': 'Temperature',
      'humidity': 'Humidity',
      'wind': 'Wind',
      'rain': 'Rain',
      'precipitation': 'Precipitation',
      'rain_chance': 'Rain Chance',
      'today': 'Today',
      'tomorrow': 'Tomorrow',

      'quick_actions': 'Quick Actions',
      'ask_ai': 'Ask AI',
      'check_crop': 'Check Crop',
      'view_market': 'View Market',
      'plan_farm': 'Plan Farm',

      'market_prices_today': 'Today’s Market Prices',
      'view_all_prices': 'View All Prices',
      'no_market_data': 'No market data available',

      'recent_activity': 'Recent Activity',
      'no_recent_activity': 'No recent activity',

      'ai_farm_notice': 'AI-powered farming insights',
      'responsible_ai': 'AI suggestions are provided for guidance.',

      'loading': 'Loading...',
      'error': 'Something went wrong',
      'try_again': 'Try Again',
      'no_data': 'No data available',

      'add_farm': 'Add Farm',
      'add_crop': 'Add Crop',
      'farm_name': 'Farm Name',
      'crop_name': 'Crop Name',
      'area': 'Area',
      'acres': 'acres',
    },

    // ============================================================
    // TELUGU
    // ============================================================
    'Telugu': {
      'home': 'హోమ్',
      'my_farm': 'నా పొలం',
      'notifications': 'నోటిఫికేషన్లు',
      'settings': 'సెట్టింగ్స్',
      'profile': 'ప్రొఫైల్',
      'ai_assistant': 'AI సహాయకుడు',
      'crop_doctor': 'పంట వైద్యుడు',
      'dashboard': 'డాష్‌బోర్డ్',
      'market_prices': 'మార్కెట్ ధరలు',
      'price_forecast': 'ధరల అంచనా',
      'farm_planner': 'వ్యవసాయ ప్రణాళిక',
      'expenses': 'ఖర్చులు',
      'crop_timeline': 'పంట కాలక్రమం',
      'ai_farm_intelligence': 'AI వ్యవసాయ మేధస్సు',

      'welcome': 'స్వాగతం',
      'good_morning': 'శుభోదయం',
      'good_afternoon': 'శుభ మధ్యాహ్నం',
      'good_evening': 'శుభ సాయంత్రం',
      'protect_crop': 'మీ పంటను రక్షించండి. తెలివిగా సాగు చేయండి.',
      'smart_farming': 'స్మార్ట్ వ్యవసాయ మేధస్సు',

      'continue': 'కొనసాగించండి',
      'save': 'సేవ్ చేయండి',
      'cancel': 'రద్దు చేయండి',
      'delete': 'తొలగించండి',
      'edit': 'మార్చండి',
      'search': 'వెతకండి',
      'add': 'జోడించండి',
      'close': 'మూసివేయండి',
      'back': 'వెనుకకు',
      'next': 'తదుపరి',
      'done': 'పూర్తయింది',

      'language': 'భాష',
      'choose_language': 'మీ భాషను ఎంచుకోండి',
      'select_language': 'భాషను ఎంచుకోండి',

      'location': 'ప్రదేశం',
      'farm': 'పొలం',
      'crop': 'పంట',
      'weather': 'వాతావరణం',
      'market': 'మార్కెట్',
      'profile_title': 'మీ ప్రొఫైల్',
      'account': 'ఖాతా',
      'privacy': 'గోప్యత',
      'security': 'భద్రత',
      'logout': 'లాగ్ అవుట్',

      'login': 'లాగిన్',
      'register': 'ఖాతా సృష్టించండి',
      'forgot_password': 'పాస్‌వర్డ్ మర్చిపోయారా',
      'email': 'ఈమెయిల్',
      'phone': 'ఫోన్',
      'password': 'పాస్‌వర్డ్',
      'confirm_password': 'పాస్‌వర్డ్ నిర్ధారించండి',
      'full_name': 'పూర్తి పేరు',

      'current_location': 'ప్రస్తుత ప్రదేశం',
      'your_farm': 'మీ పొలం',
      'your_crops': 'మీ పంటలు',
      'farm_health': 'పొలం ఆరోగ్యం',
      'healthy': 'ఆరోగ్యంగా ఉంది',
      'attention_needed': 'శ్రద్ధ అవసరం',
      'weather_alert': 'వాతావరణ హెచ్చరిక',
      'farm_alert': 'పొలం హెచ్చరిక',
      'no_alerts': 'ప్రస్తుతం హెచ్చరికలు లేవు',
      'temperature': 'ఉష్ణోగ్రత',
      'humidity': 'తేమ',
      'wind': 'గాలి',
      'rain': 'వర్షం',
      'precipitation': 'వర్షపాతం',
      'rain_chance': 'వర్షం వచ్చే అవకాశం',
      'today': 'ఈరోజు',
      'tomorrow': 'రేపు',

      'quick_actions': 'త్వరిత చర్యలు',
      'ask_ai': 'AIని అడగండి',
      'check_crop': 'పంటను తనిఖీ చేయండి',
      'view_market': 'మార్కెట్ చూడండి',
      'plan_farm': 'పొలం ప్లాన్ చేయండి',

      'market_prices_today': 'ఈరోజు మార్కెట్ ధరలు',
      'view_all_prices': 'అన్ని ధరలను చూడండి',
      'no_market_data': 'మార్కెట్ సమాచారం అందుబాటులో లేదు',

      'recent_activity': 'ఇటీవలి కార్యకలాపాలు',
      'no_recent_activity': 'ఇటీవలి కార్యకలాపాలు లేవు',

      'ai_farm_notice': 'AI ఆధారిత వ్యవసాయ సూచనలు',
      'responsible_ai': 'AI సూచనలు మార్గదర్శకత్వం కోసం మాత్రమే.',

      'loading': 'లోడ్ అవుతోంది...',
      'error': 'ఏదో సమస్య ఏర్పడింది',
      'try_again': 'మళ్లీ ప్రయత్నించండి',
      'no_data': 'సమాచారం అందుబాటులో లేదు',

      'add_farm': 'పొలాన్ని జోడించండి',
      'add_crop': 'పంటను జోడించండి',
      'farm_name': 'పొలం పేరు',
      'crop_name': 'పంట పేరు',
      'area': 'విస్తీర్ణం',
      'acres': 'ఎకరాలు',
    },

    // ============================================================
    // HINDI
    // ============================================================
    'Hindi': {
      'home': 'होम',
      'my_farm': 'मेरा खेत',
      'notifications': 'सूचनाएँ',
      'settings': 'सेटिंग्स',
      'profile': 'प्रोफ़ाइल',
      'ai_assistant': 'AI सहायक',
      'crop_doctor': 'फसल डॉक्टर',
      'dashboard': 'डैशबोर्ड',
      'market_prices': 'बाज़ार भाव',
      'price_forecast': 'मूल्य पूर्वानुमान',
      'farm_planner': 'खेत योजना',
      'expenses': 'खर्च',
      'crop_timeline': 'फसल समयरेखा',
      'ai_farm_intelligence': 'AI कृषि बुद्धिमत्ता',

      'welcome': 'स्वागत है',
      'good_morning': 'सुप्रभात',
      'good_afternoon': 'नमस्कार',
      'good_evening': 'शुभ संध्या',
      'protect_crop': 'अपनी फसल बचाएँ। समझदारी से खेती करें।',
      'smart_farming': 'स्मार्ट कृषि बुद्धिमत्ता',

      'continue': 'जारी रखें',
      'save': 'सहेजें',
      'cancel': 'रद्द करें',
      'delete': 'हटाएँ',
      'edit': 'संपादित करें',
      'search': 'खोजें',
      'add': 'जोड़ें',
      'close': 'बंद करें',
      'back': 'वापस',
      'next': 'अगला',
      'done': 'पूर्ण',

      'language': 'भाषा',
      'choose_language': 'अपनी भाषा चुनें',
      'select_language': 'भाषा चुनें',

      'location': 'स्थान',
      'farm': 'खेत',
      'crop': 'फसल',
      'weather': 'मौसम',
      'market': 'बाज़ार',
      'profile_title': 'आपकी प्रोफ़ाइल',
      'account': 'खाता',
      'privacy': 'गोपनीयता',
      'security': 'सुरक्षा',
      'logout': 'लॉग आउट',

      'login': 'लॉगिन',
      'register': 'खाता बनाएँ',
      'forgot_password': 'पासवर्ड भूल गए?',
      'email': 'ईमेल',
      'phone': 'फ़ोन',
      'password': 'पासवर्ड',
      'confirm_password': 'पासवर्ड की पुष्टि करें',
      'full_name': 'पूरा नाम',

      'current_location': 'वर्तमान स्थान',
      'your_farm': 'आपका खेत',
      'your_crops': 'आपकी फसलें',
      'farm_health': 'खेत का स्वास्थ्य',
      'healthy': 'स्वस्थ',
      'attention_needed': 'ध्यान देने की आवश्यकता',
      'weather_alert': 'मौसम चेतावनी',
      'farm_alert': 'खेत चेतावनी',
      'no_alerts': 'अभी कोई चेतावनी नहीं',
      'temperature': 'तापमान',
      'humidity': 'नमी',
      'wind': 'हवा',
      'rain': 'बारिश',
      'precipitation': 'वर्षा',
      'rain_chance': 'बारिश की संभावना',
      'today': 'आज',
      'tomorrow': 'कल',

      'quick_actions': 'त्वरित कार्य',
      'ask_ai': 'AI से पूछें',
      'check_crop': 'फसल जाँचें',
      'view_market': 'बाज़ार देखें',
      'plan_farm': 'खेत की योजना बनाएँ',

      'market_prices_today': 'आज के बाज़ार भाव',
      'view_all_prices': 'सभी भाव देखें',
      'no_market_data': 'बाज़ार की जानकारी उपलब्ध नहीं है',

      'recent_activity': 'हाल की गतिविधि',
      'no_recent_activity': 'कोई हाल की गतिविधि नहीं',

      'ai_farm_notice': 'AI आधारित कृषि सुझाव',
      'responsible_ai': 'AI सुझाव केवल मार्गदर्शन के लिए हैं।',

      'loading': 'लोड हो रहा है...',
      'error': 'कुछ गलत हो गया',
      'try_again': 'फिर कोशिश करें',
      'no_data': 'कोई जानकारी उपलब्ध नहीं',

      'add_farm': 'खेत जोड़ें',
      'add_crop': 'फसल जोड़ें',
      'farm_name': 'खेत का नाम',
      'crop_name': 'फसल का नाम',
      'area': 'क्षेत्रफल',
      'acres': 'एकड़',
    },

    // ============================================================
    // TAMIL
    // ============================================================
    'Tamil': {
      'home': 'முகப்பு',
      'my_farm': 'என் பண்ணை',
      'notifications': 'அறிவிப்புகள்',
      'settings': 'அமைப்புகள்',
      'profile': 'சுயவிவரம்',
      'ai_assistant': 'AI உதவியாளர்',
      'crop_doctor': 'பயிர் மருத்துவர்',
      'dashboard': 'டாஷ்போர்டு',
      'market_prices': 'சந்தை விலைகள்',
      'price_forecast': 'விலை முன்னறிவிப்பு',
      'farm_planner': 'பண்ணை திட்டமிடல்',
      'expenses': 'செலவுகள்',
      'crop_timeline': 'பயிர் காலவரிசை',
      'ai_farm_intelligence': 'AI விவசாய நுண்ணறிவு',

      'welcome': 'வரவேற்கிறோம்',
      'good_morning': 'காலை வணக்கம்',
      'good_afternoon': 'மதிய வணக்கம்',
      'good_evening': 'மாலை வணக்கம்',
      'protect_crop': 'உங்கள் பயிரைப் பாதுகாத்து, புத்திசாலித்தனமாக வளருங்கள்.',
      'smart_farming': 'ஸ்மார்ட் விவசாய நுண்ணறிவு',

      'continue': 'தொடரவும்',
      'save': 'சேமிக்கவும்',
      'cancel': 'ரத்து செய்யவும்',
      'delete': 'நீக்கவும்',
      'edit': 'திருத்தவும்',
      'search': 'தேடவும்',
      'add': 'சேர்க்கவும்',
      'close': 'மூடவும்',
      'back': 'பின்செல்',
      'next': 'அடுத்து',
      'done': 'முடிந்தது',

      'language': 'மொழி',
      'choose_language': 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',

      'location': 'இடம்',
      'farm': 'பண்ணை',
      'crop': 'பயிர்',
      'weather': 'வானிலை',
      'market': 'சந்தை',
      'profile_title': 'உங்கள் சுயவிவரம்',
      'account': 'கணக்கு',
      'privacy': 'தனியுரிமை',
      'security': 'பாதுகாப்பு',
      'logout': 'வெளியேறு',

      'login': 'உள்நுழைவு',
      'register': 'கணக்கை உருவாக்கவும்',
      'forgot_password': 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
      'email': 'மின்னஞ்சல்',
      'phone': 'தொலைபேசி',
      'password': 'கடவுச்சொல்',
      'confirm_password': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      'full_name': 'முழுப் பெயர்',

      'current_location': 'தற்போதைய இடம்',
      'your_farm': 'உங்கள் பண்ணை',
      'your_crops': 'உங்கள் பயிர்கள்',
      'farm_health': 'பண்ணை ஆரோக்கியம்',
      'healthy': 'ஆரோக்கியமானது',
      'attention_needed': 'கவனம் தேவை',
      'weather_alert': 'வானிலை எச்சரிக்கை',
      'farm_alert': 'பண்ணை எச்சரிக்கை',
      'no_alerts': 'தற்போது எச்சரிக்கைகள் இல்லை',
      'temperature': 'வெப்பநிலை',
      'humidity': 'ஈரப்பதம்',
      'wind': 'காற்று',
      'rain': 'மழை',
      'precipitation': 'மழைப்பொழிவு',
      'rain_chance': 'மழைக்கான வாய்ப்பு',
      'today': 'இன்று',
      'tomorrow': 'நாளை',

      'quick_actions': 'விரைவு செயல்கள்',
      'ask_ai': 'AI-யிடம் கேளுங்கள்',
      'check_crop': 'பயிரைச் சரிபார்க்கவும்',
      'view_market': 'சந்தையைப் பார்க்கவும்',
      'plan_farm': 'பண்ணையைத் திட்டமிடவும்',

      'market_prices_today': 'இன்றைய சந்தை விலைகள்',
      'view_all_prices': 'அனைத்து விலைகளையும் பார்க்கவும்',
      'no_market_data': 'சந்தை தகவல் இல்லை',

      'recent_activity': 'சமீபத்திய செயல்பாடுகள்',
      'no_recent_activity': 'சமீபத்திய செயல்பாடுகள் இல்லை',

      'ai_farm_notice': 'AI அடிப்படையிலான விவசாய ஆலோசனைகள்',
      'responsible_ai': 'AI பரிந்துரைகள் வழிகாட்டுதலுக்காக மட்டுமே.',

      'loading': 'ஏற்றப்படுகிறது...',
      'error': 'ஏதோ தவறு ஏற்பட்டது',
      'try_again': 'மீண்டும் முயற்சிக்கவும்',
      'no_data': 'தகவல் இல்லை',

      'add_farm': 'பண்ணையைச் சேர்க்கவும்',
      'add_crop': 'பயிரைச் சேர்க்கவும்',
      'farm_name': 'பண்ணையின் பெயர்',
      'crop_name': 'பயிரின் பெயர்',
      'area': 'பரப்பளவு',
      'acres': 'ஏக்கர்',
    },

    // ============================================================
    // KANNADA
    // ============================================================
    'Kannada': {
      'home': 'ಮುಖಪುಟ',
      'my_farm': 'ನನ್ನ ಕೃಷಿ',
      'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
      'settings': 'ಸೆಟ್ಟಿಂಗ್ಸ್',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'ai_assistant': 'AI ಸಹಾಯಕ',
      'crop_doctor': 'ಬೆಳೆ ವೈದ್ಯ',
      'dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'market_prices': 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು',
      'price_forecast': 'ಬೆಲೆ ಮುನ್ಸೂಚನೆ',
      'farm_planner': 'ಕೃಷಿ ಯೋಜನೆ',
      'expenses': 'ವೆಚ್ಚಗಳು',
      'crop_timeline': 'ಬೆಳೆ ಸಮಯರೇಖೆ',
      'ai_farm_intelligence': 'AI ಕೃಷಿ ಬುದ್ಧಿಮತ್ತೆ',

      'welcome': 'ಸ್ವಾಗತ',
      'good_morning': 'ಶುಭೋದಯ',
      'good_afternoon': 'ಶುಭ ಮಧ್ಯಾಹ್ನ',
      'good_evening': 'ಶುಭ ಸಂಜೆ',
      'protect_crop': 'ನಿಮ್ಮ ಬೆಳೆಯನ್ನು ರಕ್ಷಿಸಿ. ಬುದ್ಧಿವಂತಿಕೆಯಿಂದ ಕೃಷಿ ಮಾಡಿ.',
      'smart_farming': 'ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಬುದ್ಧಿಮತ್ತೆ',

      'continue': 'ಮುಂದುವರಿಸಿ',
      'save': 'ಉಳಿಸಿ',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'delete': 'ಅಳಿಸಿ',
      'edit': 'ತಿದ್ದು',
      'search': 'ಹುಡುಕಿ',
      'add': 'ಸೇರಿಸಿ',
      'close': 'ಮುಚ್ಚಿ',
      'back': 'ಹಿಂದೆ',
      'next': 'ಮುಂದೆ',
      'done': 'ಮುಗಿದಿದೆ',

      'language': 'ಭಾಷೆ',
      'choose_language': 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'select_language': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',

      'location': 'ಸ್ಥಳ',
      'farm': 'ಕೃಷಿ',
      'crop': 'ಬೆಳೆ',
      'weather': 'ಹವಾಮಾನ',
      'market': 'ಮಾರುಕಟ್ಟೆ',
      'profile_title': 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್',
      'account': 'ಖಾತೆ',
      'privacy': 'ಗೌಪ್ಯತೆ',
      'security': 'ಭದ್ರತೆ',
      'logout': 'ಲಾಗ್ ಔಟ್',

      'login': 'ಲಾಗಿನ್',
      'register': 'ಖಾತೆ ರಚಿಸಿ',
      'forgot_password': 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರುವಿರಾ?',
      'email': 'ಇಮೇಲ್',
      'phone': 'ಫೋನ್',
      'password': 'ಪಾಸ್‌ವರ್ಡ್',
      'confirm_password': 'ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
      'full_name': 'ಪೂರ್ಣ ಹೆಸರು',

      'current_location': 'ಪ್ರಸ್ತುತ ಸ್ಥಳ',
      'your_farm': 'ನಿಮ್ಮ ಕೃಷಿ',
      'your_crops': 'ನಿಮ್ಮ ಬೆಳೆಗಳು',
      'farm_health': 'ಕೃಷಿ ಆರೋಗ್ಯ',
      'healthy': 'ಆರೋಗ್ಯಕರ',
      'attention_needed': 'ಗಮನ ಅಗತ್ಯ',
      'weather_alert': 'ಹವಾಮಾನ ಎಚ್ಚರಿಕೆ',
      'farm_alert': 'ಕೃಷಿ ಎಚ್ಚರಿಕೆ',
      'no_alerts': 'ಈಗ ಯಾವುದೇ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ',
      'temperature': 'ತಾಪಮಾನ',
      'humidity': 'ಆರ್ದ್ರತೆ',
      'wind': 'ಗಾಳಿ',
      'rain': 'ಮಳೆ',
      'precipitation': 'ಮಳೆಯ ಪ್ರಮಾಣ',
      'rain_chance': 'ಮಳೆಯ ಸಾಧ್ಯತೆ',
      'today': 'ಇಂದು',
      'tomorrow': 'ನಾಳೆ',

      'quick_actions': 'ತ್ವರಿತ ಕಾರ್ಯಗಳು',
      'ask_ai': 'AI ಕೇಳಿ',
      'check_crop': 'ಬೆಳೆ ಪರಿಶೀಲಿಸಿ',
      'view_market': 'ಮಾರುಕಟ್ಟೆ ನೋಡಿ',
      'plan_farm': 'ಕೃಷಿ ಯೋಜಿಸಿ',

      'market_prices_today': 'ಇಂದಿನ ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು',
      'view_all_prices': 'ಎಲ್ಲಾ ಬೆಲೆಗಳನ್ನು ನೋಡಿ',
      'no_market_data': 'ಮಾರುಕಟ್ಟೆ ಮಾಹಿತಿ ಲಭ್ಯವಿಲ್ಲ',

      'recent_activity': 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
      'no_recent_activity': 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆಗಳಿಲ್ಲ',

      'ai_farm_notice': 'AI ಆಧಾರಿತ ಕೃಷಿ ಸಲಹೆಗಳು',
      'responsible_ai': 'AI ಸಲಹೆಗಳು ಮಾರ್ಗದರ್ಶನಕ್ಕಾಗಿ ಮಾತ್ರ.',

      'loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
      'error': 'ಏನೋ ತಪ್ಪಾಗಿದೆ',
      'try_again': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
      'no_data': 'ಯಾವುದೇ ಮಾಹಿತಿ ಲಭ್ಯವಿಲ್ಲ',

      'add_farm': 'ಕೃಷಿ ಸೇರಿಸಿ',
      'add_crop': 'ಬೆಳೆ ಸೇರಿಸಿ',
      'farm_name': 'ಕೃಷಿಯ ಹೆಸರು',
      'crop_name': 'ಬೆಳೆಯ ಹೆಸರು',
      'area': 'ವಿಸ್ತೀರ್ಣ',
      'acres': 'ಎಕರೆ',
    },

    // ============================================================
    // MALAYALAM
    // ============================================================
    'Malayalam': {
      'home': 'ഹോം',
      'my_farm': 'എന്റെ കൃഷിയിടം',
      'notifications': 'അറിയിപ്പുകൾ',
      'settings': 'ക്രമീകരണങ്ങൾ',
      'profile': 'പ്രൊഫൈൽ',
      'ai_assistant': 'AI സഹായി',
      'crop_doctor': 'വിള ഡോക്ടർ',
      'dashboard': 'ഡാഷ്ബോർഡ്',
      'market_prices': 'വിപണി വിലകൾ',
      'price_forecast': 'വില പ്രവചനം',
      'farm_planner': 'കൃഷി ആസൂത്രണം',
      'expenses': 'ചെലവുകൾ',
      'crop_timeline': 'വിള സമയരേഖ',
      'ai_farm_intelligence': 'AI കൃഷി ബുദ്ധി',

      'welcome': 'സ്വാഗതം',
      'good_morning': 'സുപ്രഭാതം',
      'good_afternoon': 'ശുഭ ഉച്ചതിരിഞ്ഞ്',
      'good_evening': 'ശുഭ സായാഹ്നം',
      'protect_crop': 'നിങ്ങളുടെ വിള സംരക്ഷിക്കൂ. ബുദ്ധിപൂർവ്വം കൃഷി ചെയ്യൂ.',
      'smart_farming': 'സ്മാർട്ട് കൃഷി ബുദ്ധി',

      'continue': 'തുടരുക',
      'save': 'സേവ് ചെയ്യുക',
      'cancel': 'റദ്ദാക്കുക',
      'delete': 'ഇല്ലാതാക്കുക',
      'edit': 'തിരുത്തുക',
      'search': 'തിരയുക',
      'add': 'ചേർക്കുക',
      'close': 'അടയ്ക്കുക',
      'back': 'പിന്നിലേക്ക്',
      'next': 'അടുത്തത്',
      'done': 'പൂർത്തിയായി',

      'language': 'ഭാഷ',
      'choose_language': 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
      'select_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',

      'location': 'സ്ഥലം',
      'farm': 'കൃഷിയിടം',
      'crop': 'വിള',
      'weather': 'കാലാവസ്ഥ',
      'market': 'വിപണി',
      'profile_title': 'നിങ്ങളുടെ പ്രൊഫൈൽ',
      'account': 'അക്കൗണ്ട്',
      'privacy': 'സ്വകാര്യത',
      'security': 'സുരക്ഷ',
      'logout': 'ലോഗ് ഔട്ട്',

      'login': 'ലോഗിൻ',
      'register': 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
      'forgot_password': 'പാസ്‌വേഡ് മറന്നോ?',
      'email': 'ഇമെയിൽ',
      'phone': 'ഫോൺ',
      'password': 'പാസ്‌വേഡ്',
      'confirm_password': 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
      'full_name': 'പൂർണ്ണ പേര്',

      'current_location': 'നിലവിലെ സ്ഥലം',
      'your_farm': 'നിങ്ങളുടെ കൃഷിയിടം',
      'your_crops': 'നിങ്ങളുടെ വിളകൾ',
      'farm_health': 'കൃഷിയിട ആരോഗ്യനില',
      'healthy': 'ആരോഗ്യമുള്ളത്',
      'attention_needed': 'ശ്രദ്ധ ആവശ്യമാണ്',
      'weather_alert': 'കാലാവസ്ഥാ മുന്നറിയിപ്പ്',
      'farm_alert': 'കൃഷിയിട മുന്നറിയിപ്പ്',
      'no_alerts': 'ഇപ്പോൾ മുന്നറിയിപ്പുകളില്ല',
      'temperature': 'താപനില',
      'humidity': 'ഈർപ്പം',
      'wind': 'കാറ്റ്',
      'rain': 'മഴ',
      'precipitation': 'മഴയുടെ അളവ്',
      'rain_chance': 'മഴയ്ക്ക് സാധ്യത',
      'today': 'ഇന്ന്',
      'tomorrow': 'നാളെ',

      'quick_actions': 'ദ്രുത പ്രവർത്തനങ്ങൾ',
      'ask_ai': 'AI-യോട് ചോദിക്കുക',
      'check_crop': 'വിള പരിശോധിക്കുക',
      'view_market': 'വിപണി കാണുക',
      'plan_farm': 'കൃഷി ആസൂത്രണം ചെയ്യുക',

      'market_prices_today': 'ഇന്നത്തെ വിപണി വിലകൾ',
      'view_all_prices': 'എല്ലാ വിലകളും കാണുക',
      'no_market_data': 'വിപണി വിവരങ്ങൾ ലഭ്യമല്ല',

      'recent_activity': 'സമീപകാല പ്രവർത്തനങ്ങൾ',
      'no_recent_activity': 'സമീപകാല പ്രവർത്തനങ്ങളില്ല',

      'ai_farm_notice': 'AI അടിസ്ഥാനത്തിലുള്ള കൃഷി നിർദ്ദേശങ്ങൾ',
      'responsible_ai': 'AI നിർദ്ദേശങ്ങൾ മാർഗ്ഗനിർദ്ദേശത്തിനായി മാത്രം.',

      'loading': 'ലോഡ് ചെയ്യുന്നു...',
      'error': 'എന്തോ തെറ്റ് സംഭവിച്ചു',
      'try_again': 'വീണ്ടും ശ്രമിക്കുക',
      'no_data': 'വിവരങ്ങൾ ലഭ്യമല്ല',

      'add_farm': 'കൃഷിയിടം ചേർക്കുക',
      'add_crop': 'വിള ചേർക്കുക',
      'farm_name': 'കൃഷിയിടത്തിന്റെ പേര്',
      'crop_name': 'വിളയുടെ പേര്',
      'area': 'വിസ്തീർണ്ണം',
      'acres': 'ഏക്കർ',
    },
  };

  /// Returns the translated text for the current selected language.
  ///
  /// If a translation is not yet available for a language,
  /// English is used as the fallback.
  static String tr(String key) {
    final String language = appCurrentLanguage.value;

    final Map<String, String>? currentTranslations =
        translations[language];

    if (currentTranslations != null &&
        currentTranslations.containsKey(key)) {
      return currentTranslations[key]!;
    }

    final Map<String, String> englishTranslations =
        translations['English']!;

    return englishTranslations[key] ?? key;
  }
}
